name: My First Workflow
on: workflow_dispatch
jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run:  echo "Hello, World"
      - name: Say goodbye
        run: echo "Done - bye!"
        
